# config context path to "/" by setting an empty string
server:
  contextPath:

jwt:
  header: Authorization
  secret: herodotSecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh

logging:
  level:
    org.springframework:
      security: DEBUG

spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  jpa:
    hibernate:
      # possible values: validate | update | create | create-drop
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://ec2-79-125-125-97.eu-west-1.compute.amazonaws.com:5432/d5fq9h38m2gtjl?sslmode=require
    username: dufhjxlykjeaav
    password: 96398d6095dfd4e520a7e2100442cb7e487189989c1d73d1823936983d7467c3